HPC_ANALYSIS_FOLDER: 'GatorSeq_Analysis'
PADDING_SIZE: '250'
TARGET_BED_FILE: 'GatorseqV2_117_GenePanel_Translocation_MSI_SampleID_AIMs_Gender_probes.bed'
MERGED_TARGET_BED_FILE: 'GatorseqV2_117_GenePanel_Translocation_MSI_SampleID_AIMs_Gender_probes_merged.bed'
PADDED_TARGET_BED_FILE: 'GatorseqV2_117_GenePanel_Translocation_MSI_SampleID_AIMs_Gender_Targets_250bp_padded.bed'
GSBW_VERSION: '1.3'
